version: '3'

services:
  # Первая реплика приложения
  app1:
    build: .
    container_name: app1
    ports:
      - "8081:8080"
    networks:
      - app-network

  # Вторая реплика приложения
  app2:
    build: .
    container_name: app2
    ports:
      - "8082:8080"
    networks:
      - app-network

  # Третья реплика приложения
  app3:
    build: .
    container_name: app3
    ports:
      - "8083:8080"
    networks:
      - app-network

  # NGINX для балансировки нагрузки
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
